name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer les dépendances (si nécessaire)
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install mkdocs

      # Étape 3 : Construire la documentation avec MkDocs (ou autre outil)
      - name: Build documentation
        run: mkdocs build

      # Étape 4 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
